# Generated by Django 3.2.3 on 2022-04-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20220419_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image3',
            field=models.ImageField(default='default_author.jpg', upload_to='author_pics'),
        ),
        migrations.AddField(
            model_name='genre',
            name='image2',
            field=models.ImageField(default='default_genre.jpg', upload_to='genre_pics'),
        ),
    ]
