# Generated by Django 3.2.3 on 2022-04-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20220421_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image3',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='image2',
            new_name='picture',
        ),
    ]
